apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-service
  namespace: team-a-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-service
        version: v1
    spec:
      containers:
      - name: inventory-service
        image: {{image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
      imagePullSecrets:
        - name: ecr-secret
