apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{service}}
  namespace: {{namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{service}}
        version: v1
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{profiles}}
      imagePullSecrets:
        - name: ecr-secret
