spring:
  datasource:
    url: jdbc:mysql://localhost/dmall_inventory_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abcd1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: false
  flyway:
    locations: "classpath:/db/migration"